#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then run 'script.sh' with that shell:
#
#           ksh gradlew
#
#       Or, you can set the 'gradle.shellCheckInterpreter' property to the
#       interpreter of your choice.
#
#   (2) This script points at the properties which Gradle has placed in
#       gradle/wrapper/gradle-wrapper.properties. If you don't have a
#       gradle-wrapper.properties file, generate it.
#
#   (3) This script attempts to find a minimum version of Java to execute
#       the Gradle commands. If you set JAVA_HOME to a location of a JDK, the
#       script will use that. If not, it will attempt to find a JDK using the
#       'java' command. If neither works, Gradle will exit.
#
#   (4) The default Gradle version is the one specified in the
#       gradle/wrapper/gradle-wrapper.properties file. If that file is missing,
#       the wrapper version is the version of Gradle used to generate the
#       wrapper script. You can override the Gradle version by setting
#       GRADLE_WRAPPER_VERSION, but this should be unnecessary.
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$(ls -ld "$app_path")
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

# This is normally unused
# shellcheck disable=SC2034
APP_BASE_NAME=${0##*/}
APP_HOME=$(cd "${APP_HOME:-./}" && pwd -P) || exit

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$(uname)" in
  CYGWIN* )
    cygwin=true
    ;;
  Darwin* )
    darwin=true
    ;;
  MSYS* | MINGW* )
    msys=true
    ;;
  NONSTOP* )
    nonstop=true
    ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    if ! command -v java >/dev/null 2>&1
    then
        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case $MAX_FD in #(
      max*)
        # In POSIX sh, ulimit -H -n is not available. Use 'uname -n' because 'ulimit' might not be available.
        # Also, ulimit might not be available in some shells.
        # So if we can't find a working ulimit, just move on.
        if command -v ulimit >/dev/null 2>&1
        then
            ulimit -n -s || true
        fi
        ;;
      *)
        ulimit -n "$MAX_FD" || true
        ;;
    esac
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * -D...appname settings
#   * --module-path (only if needed)
#   * DEFAULT_JVM_OPTS, JAVA_OPTS, and GRADLE_OPTS environment variables.

# For Cygwin or MSYS, switch paths to Windows format before running java
if "$cygwin" || "$msys" ; then
    APP_HOME=$(cygpath --path --mixed "$APP_HOME")
    CLASSPATH=$(cygpath --path --mixed "$CLASSPATH")

    JAVACMD=$(cygpath --unix "$JAVACMD")

    # Now convert the arguments - kludge to limit ourselves to /bin/sh
    for arg do
        if
            case $arg in                                #(
              -*)   false ;;                            # don't mess with options #(
              /?*)  t=${arg#/} t=/${t%%/*}              # looks like a POSIX filepath
                    [ -e "$t" ] ;;                      #(
              *)    false ;;
            esac
        then
            arg=$(cygpath --path --ignore --mixed "$arg")
        fi
        # Roll the args list around exactly as many times as the number of
        # args, so each arg winds up back at the beginning.
        set -- "$@" "$arg"
    done
fi

# Collect all arguments for the java command;
#   * $DEFAULT_JVM_OPTS, $JAVA_OPTS, and $GRADLE_OPTS can contain fragments of
#     shell script including quotes and variable substitutions, so put them in
#     double quotes to make sure that they get re-expanded; and
#   * put everything else in single quotes, so that it's not re-expanded.

set -- \
        "-Dorg.gradle.appname=$APP_BASE_NAME" \
        -classpath "$CLASSPATH" \
        org.gradle.wrapper.GradleWrapperMain \
        "$@"

# Stop when "xargs" is not available.
if ! command -v xargs >/dev/null 2>&1
then
    die "xargs is not available"
fi

# Use "xargs" to parse quoted args.
#
# With -n1 it outputs one arg per line, with the quotes and backslashes removed.
#
# In Bash we could simply go:
#
#   readarray ARGS < <( xargs -n1 <<<"$var" ) &&
#   set -- "${ARGS[@]}" "$@"
#
# but POSIX shell has neither arrays nor command substitution, so instead we
# post-process each arg (as a line of input to sed) to backslash-escape any
# character that might be a pipe or carriage return, then wrap the whole line
# in double quotes, and pass it to "eval sed -n ..." to evaluate the escaped
# quotes as literal quotes, then use 'eval' to actually run the command.
#
# In POSIX it is not possible to use 'xargs' to parse a single argument with
# quotes because with '-n1', it splits the argument on the first space, not
# respecting quotes. So we use a different path.
#
# xargs is also not available on some platforms. This fallback will hopefully
# work.
#
parse_xargs_args () {
    set -- "$(xargs -n1 <"$1" | sed -e 's/[\x01-\x1f\x7f]/\\&/g' -e 's/\([^\\]*\(\\.[^\\]*\)*\)/\\"\1\\"/g')" "$@"
    set -- "$(printf '%s\n' "$1" | sed -e 's/\(["'"'"'`$\\]\)/\\\1/g')" "$@"
    eval set -- "$(printf '%s=%s' -- "$1" "$2")" "$3"
}

# For darwin, add LD_LIBRARY_PATH to DYLD_LIBRARY_PATH
if $darwin; then
    LD_LIBRARY_PATH_USR=$LD_LIBRARY_PATH
    export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:$LD_LIBRARY_PATH_USR
fi

# Find the java cmd in the PATH
# shellcheck disable=SC2120
# We are 'source-ing' this script so we don't actually execute the 'find_java_cmd' function,
# we just want the variable. We use 'command -v' to find the java command
JAVACMD=$(command -v java 2>/dev/null) || die "Unable to find java in PATH. Please set JAVA_HOME."

# Escape application args
save () {
    for i do printf %s\\n "$i" | sed "s/'/'\\\\''/g;1s/^/'/;\$s/\$/' \\\\/"; done
    echo " "
}
APP_ARGS=$(save "$@")

# Collect all arguments for the java command;
#   * $DEFAULT_JVM_OPTS, $JAVA_OPTS, and $GRADLE_OPTS can contain fragments of
#     shell script including quotes and variable substitutions, so put them in
#     double quotes to make sure that they get re-expanded; and
#   * put everything else in single quotes, so that it's not re-expanded.
set -- \
        "-Dorg.gradle.appname=$APP_BASE_NAME" \
        -classpath "$CLASSPATH" \
        org.gradle.wrapper.GradleWrapperMain \
        "$@"

# Stop when "xargs" is not available.
if ! command -v xargs >/dev/null 2>&1
then
    die "xargs is not available"
fi

# Use "xargs" to parse quoted args.
#
# With -n1 it outputs one arg per line, with the quotes and backslashes removed.
#
# In Bash we could simply go:
#
#   readarray ARGS < <( xargs -n1 <<<"$var" ) &&
#   set -- "${ARGS[@]}" "$@"
#
# but POSIX shell has neither arrays nor command substitution, so instead we
# post-process each arg (as a line of input to sed) to backslash-escape any
# character that might be a pipe or carriage return, then wrap the whole line
# in double quotes, and pass it to "eval sed -n ..." to evaluate the escaped
# quotes as literal quotes, then use 'eval' to actually run the command.
#
# In POSIX it is not possible to use 'xargs' to parse a single argument with
# quotes because with '-n1', it splits the argument on the first space, not
# respecting quotes. So we use a different path.
#
# xargs is also not available on some platforms. This fallback will hopefully
# work.
#
parse_xargs_args () {
    set -- "$(xargs -n1 <"$1" | sed -e 's/[\x01-\x1f\x7f]/\\&/g' -e 's/\([^\\]*\(\\.[^\\]*\)*\)/\\"\1\\"/g')" "$@"
    set -- "$(printf '%s\n' "$1" | sed -e 's/\(["'"'"'`$\\]\)/\\\1/g')" "$@"
    eval set -- "$(printf '%s=%s' -- "$1" "$2")" "$3"
}

# For darwin, add LD_LIBRARY_PATH to DYLD_LIBRARY_PATH
if $darwin; then
    LD_LIBRARY_PATH_USR=$LD_LIBRARY_PATH
    export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:$LD_LIBRARY_PATH_USR
fi

# Evaluate the command with the escaped args
eval set -- "$APP_ARGS"

# Execute Gradle
exec "$JAVACMD" "$@"
